# Define common configurations
working_directory: &working_directory
  working_directory: /tmp/app

# Filter template: only tags and develop branch
filter_only_tags_develop: &filter_only_tags_develop
  filters:
    tags:
      only: /.*/
    branches:
      only: /develop/

# Filter template: only develop branch
filter_only_develop: &filter_only_develop
  filters:
    tags:
      ignore: /.*/
    branches:
      only: /develop/

# Filter template: allow all
filter_all: &filter_all
  filters:
    tags:
      only: /.*/
    branches:
      only: /.*/

# Filter template: only tags
filter_only_tags: &filter_only_tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

# Define node build configurations
node_config: &node_config
  docker:
    - image: circleci/node:10
  <<: *working_directory

# Download cached dependencies
restore_npm_cache: &restore_npm_cache
  restore_cache:
    keys:
      - node-dependencies-{{ checksum "yarn.lock" }}
      # fallback to using the latest cache if no exact match is found
      - node-dependencies-

# Save cache dependencies
save_npm_cache: &save_npm_cache
  save_cache:
    paths:
      - node_modules
    key: node-dependencies-{{ checksum "yarn.lock" }}

# Download cached workspace
restore_workspace: &restore_workspace
  attach_workspace:
    # Must be absolute path or relative path from working_directory
    at: .

# Save all actual files
save_workspace: &save_workspace
  persist_to_workspace:
    # Must be relative path from working_directory
    root: .
    # Must be relative path from root
    paths:
      - .


version: 2
jobs:
  install_dependencies:
    <<: *node_config
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install Node Dependencies
          command: yarn install
      - *save_npm_cache
      - *save_workspace

  test:
    <<: *node_config
    steps:
      - *restore_workspace
      - run:
          name: Unit tests
          command: yarn test


workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies:
          <<: *filter_all
      - test:
          requires:
            - install_dependencies
          <<: *filter_all
