name: Playground

on:
  push:
    branches:
      - playground

jobs:

  playground:
    if: github.event.event_name == push
    name: Playground stuff
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
