name: Playground

on:
  push:
    branches:
      - playground

jobs:

  playground:
    name: Playground stuff
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/workflows
